/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.nmt.model;

/**
 *
 * @author bryce
 */
public enum Occupation {
    AGRICULTURE,
    CARE_GIVER,
    CHILD_CARE,
    CITY,
    CLEANING_SERVICE,
    CONGREGATE_CARE,
    CONSTRUCTION,
    CONVENIENCE_STORE,
    CORRECTIONS,
    COUNTY,
    COURT_PERSONNEL,
    ENERGY,
    FACTORY_FOOD_PROCESSING,
    FEDERAL_EMPLOYEE,
    FINANCIAL_SERVICE,
    FIRST_RESPONDER,
    FOOD_SERVICE,
    GROCERY_STORE,
    HEALTHCARE,
    HIGHER_EDUCATION,
    INDIGENT_CARE,
    IT_COMMUNICATION,
    K_12_EDUCATOR,
    LEGAL_ACCOUNTING,
    MANUFACTURING,
    MEDIA,
    MEDICAL_ENGINEERING_SUPPLIES,
    MORTUARY_FUNERAL_SERVICE,
    NON_FOOD_RETAIL,
    PUBLIC_HEALTH,
    PUBLIC_SAFETY_ENGINEERING,
    PUBLIC_SAFETY_NONMEDICAL_FIRST_RESPONDER,
    PUBLIC_TRANSIT,
    RESEARCH_LABORATORIES,
    SCHOOL_STAFF,
    SHELTER_HOUSING,
    STATE,
    STUDENT,
    TRANSPORTATION_LOGISTICS,
    US_POSTAL_SERVICE,
    VETERINARY_SERVICE,
    WATER_WASTEWATER,
    UNEMPLOYED,
    RETIRED,
    OTHER;
}
